//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGerenciarCargosVagos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VAGAS_ORGAO
    {
        public string NOME_MES { get; set; }
        public int ORGAO { get; set; }
        public string NOME_ORGAO { get; set; }
        public string SIGLA_ORGAO { get; set; }
        public Nullable<int> APROVADA { get; set; }
        public Nullable<int> DISTRIBUIDA { get; set; }
        public Nullable<int> OCUPADA { get; set; }
        public Nullable<int> VAGAS { get; set; }
    }
}
